# Generated by Django 3.0.3 on 2020-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics'),
        ),
    ]
