# Generated by Django 3.0.3 on 2020-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200526_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/defaults/default8.png', upload_to='media/profile_pics'),
        ),
    ]
