# Generated by Django 3.0.3 on 2020-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200529_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/defaults/default2.png', upload_to='media/profile_pics'),
        ),
    ]
