# Generated by Django 3.0.3 on 2020-06-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
