# Generated by Django 3.0.3 on 2020-06-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200529_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='media/article_pics/default.png', upload_to='media/article_pics'),
        ),
    ]
