# Generated by Django 3.0.3 on 2020-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='media/article_pics/default.jpg', upload_to='media/article_pics'),
        ),
    ]
