# Generated by Django 3.0.3 on 2020-06-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='profile_pic',
        ),
    ]
