# Generated by Django 3.0.3 on 2020-06-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
