# Generated by Django 3.0.3 on 2020-06-24 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='drafts',
        ),
        migrations.AddField(
            model_name='draft',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='draft',
            name='cover',
            field=models.ImageField(default='media/article_pics/default.jpg', upload_to='media/article_pics'),
        ),
        migrations.AddField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='draft',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='draft',
            name='subtitle',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='draft',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
