# Generated by Django 3.0.3 on 2020-06-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200624_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='last_name',
        ),
    ]
