# Generated by Django 3.0.3 on 2020-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200624_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='cover',
            field=models.ImageField(default='media/draft_pics/default.jpg', upload_to='media/draft_pics'),
        ),
    ]
