// User Authentication
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_FAIL_TIMEOUT = "AUTH_FAIL_TIMEOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// User Profiles
export const FETCH_CURR_USER_REQUEST = "FETCH_CURR_USER_REQUEST";
export const FETCH_CURR_USER_SUCCESS = "FETCH_CURR_USER_SUCCESS";
export const FETCH_CURR_USER_FAILURE = "FETCH_CURR_USER_FAILURE";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAILURE = "CREATE_PROFILE_FAILURE";
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
export const VIEW_PROFILE_REQUEST = "VIEW_PROFILE_REQUEST";
export const VIEW_PROFILE_SUCCESS = "VIEW_PROFILE_SUCCESS";
export const VIEW_PROFILE_FAILURE = "VIEW_PROFILE_FAILURE";
export const CURR_USER_LOGOUT = "CURR_USER_LOGOUT";

// Articles
export const FETCH_ALL_ARTICLES_REQUEST = "FETCH_ALL_ARTICLES_REQUEST";
export const FETCH_ALL_ARTICLES_SUCCESS = "FETCH_ALL_ARTICLES_SUCCESS";
export const FETCH_ALL_ARTICLES_FAILURE = "FETCH_ALL_ARTICLES_FAILURE";
export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";
export const CREATE_ARTICLE_REQUEST = "CREATE_ARTICLE_REQUEST";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";
export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAILURE = "EDIT_ARTICLE_FAILURE";
export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE";
export const CLEAR_ARTICLE_STATUS = "CLEAR_ARTICLE_STATUS";

// Drafts
export const FETCH_DRAFTS_REQUEST = "FETCH_DRAFTS_REQUEST";
export const FETCH_DRAFTS_SUCCESS = "FETCH_DRAFTS_SUCCESS";
export const FETCH_DRAFTS_FAILURE = "FETCH_DRAFTS_FAILURE";
export const CREATE_DRAFT_REQUEST = "CREATE_DRAFT_REQUEST";
export const CREATE_DRAFT_SUCCESS = "CREATE_DRAFT_SUCCESS";
export const CREATE_DRAFT_FAILURE = "CREATE_DRAFT_FAILURE";
export const DELETE_DRAFT_REQUEST = "DELETE_DRAFT_REQUEST";
export const DELETE_DRAFT_SUCCESS = "DELETE_DRAFT_SUCCESS";
export const DELETE_DRAFT_FAILURE = "DELETE_DRAFT_FAILURE";
