# Generated by Django 3.0.3 on 2020-07-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Learn',
            new_name='Topic',
        ),
    ]
