# Generated by Django 3.0.3 on 2020-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20200724_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
