# Generated by Django 3.0.3 on 2020-07-24 22:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_topic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='contributers',
        ),
        migrations.AddField(
            model_name='topic',
            name='contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=5), default=[], size=None),
        ),
        migrations.AddField(
            model_name='topic',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
